# Generated by Django 5.2 on 2025-04-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formularios', '0002_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomes', models.CharField(max_length=50)),
                ('emails', models.CharField(max_length=50)),
            ],
        ),
    ]
