# Generated by Django 5.2 on 2025-04-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_alter_usuarios_senhas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='senhas',
            field=models.CharField(default='', max_length=50),
        ),
    ]
